## 环境搭建(基于anaconda,cpu版本)

```shell
conda create -n pytorch python=3.6
conda activate pytorch
# conda国内源用不了，用pip装
# conda install pytorch-cpu torchvision-cpu -c pytorch
pip install torch torchvision
```
- 测试下
```python
import torch
print(torch.__version__)
'1.1.0'
```
- 安装jupyter:`pip install jupyter`

## 基本操作

In [20]:
import torch

- 创建一个5*3的未初始化矩阵

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[1.2612e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.7215e-30, 1.4013e-45, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


- 创建一个随机初始化矩阵

In [7]:
x=torch.rand(5,3)
print(x)

tensor([[0.6306, 0.0139, 0.0380],
        [0.0561, 0.9127, 0.5848],
        [0.7276, 0.3660, 0.8764],
        [0.5534, 0.9967, 0.0024],
        [0.7386, 0.1533, 0.0286]])


- 创建一个全0的矩阵，指定数据类型为long

In [8]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- 使用list创建tensor

In [10]:
x=torch.tensor([[3,5,6,8],[2,4,6,9]])
print(x)

tensor([[3, 5, 6, 8],
        [2, 4, 6, 9]])


- 根据现有的张量创建张量，可以额外设置属性覆盖原有继承的属性

In [23]:
x=x.new_ones(5,6) #new_ones()会保持 x 原有的属性
print(x.dtype)
print(x)
x=x.new_ones(5,6,dtype=torch.float) # 声明那个就覆盖那个
print(x.dtype)
print(x)


torch.float64
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.float32
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [24]:
x = torch.randn_like(x, dtype=torch.double)
print(x)
print(x.size()) # 获取张量的shape属性

tensor([[-0.2556, -0.6149,  0.1031, -0.7567,  0.4570, -1.7502],
        [-0.7812,  0.4714,  1.0411, -2.3738,  0.2339,  1.0978],
        [-1.8101,  0.0969, -2.8165, -0.7049, -0.6684, -0.5910],
        [ 1.0470, -0.9930,  2.7638,  0.8098, -0.4576, -0.6748],
        [ 0.3987,  1.9479, -0.1405, -0.4190,  0.3139,  1.3922]],
       dtype=torch.float64)
torch.Size([5, 6])


- 加法

In [28]:
y1 = torch.rand(5, 6,dtype=torch.double) 
print(x + y1) # 需要类型保持一致

tensor([[ 0.0677, -0.5265,  0.4787,  0.0115,  0.4908, -0.9333],
        [-0.1396,  1.3780,  1.8048, -1.7193,  0.5380,  1.6352],
        [-0.9253,  0.9837, -1.9807, -0.2989, -0.3932,  0.1182],
        [ 1.8643, -0.2414,  2.8462,  0.8938, -0.1084,  0.2608],
        [ 0.9144,  2.2140,  0.3263, -0.3531,  0.4514,  2.2828]],
       dtype=torch.float64)


In [30]:
y2 = torch.rand(5, 6,dtype=torch.double) 
print(torch.add(x,y2))

tensor([[ 0.2845, -0.3251,  0.5284, -0.6453,  1.4314, -1.5641],
        [ 0.2123,  1.1909,  1.3762, -2.2693,  1.0012,  1.3283],
        [-1.3866,  0.2038, -2.4345, -0.3131, -0.2016,  0.3787],
        [ 1.0898, -0.0245,  3.6384,  1.3068,  0.3205,  0.2546],
        [ 0.8418,  2.9421,  0.7061, -0.3817,  1.0483,  1.7234]],
       dtype=torch.float64)


In [34]:
out=torch.empty(5, 6,dtype=torch.double)
y3 = torch.rand(5, 6,dtype=torch.double) 
torch.add(x,y3,out=out) # 指定out
print(out)

tensor([[-0.0190,  0.2301,  0.4980, -0.0196,  0.5239, -1.3210],
        [-0.7384,  1.0833,  1.2184, -1.3988,  1.1273,  1.9711],
        [-1.3116,  0.5075, -1.8717,  0.0325, -0.0639,  0.2848],
        [ 1.6740, -0.9400,  3.2794,  1.5510, -0.4248,  0.0037],
        [ 1.0638,  2.2850, -0.1177,  0.3693,  0.5190,  1.5973]],
       dtype=torch.float64)


In [36]:
y.add_(x) 
print(y)

tensor([[ 0.2270, -0.3608,  1.0462, -0.6915,  1.7523, -2.8591],
        [-0.6079,  1.2486,  2.7740, -3.9970,  0.7881,  2.4661],
        [-3.3477,  1.1527, -5.5187, -0.8716, -0.7509, -0.5952],
        [ 2.6154, -1.0364,  6.3401,  1.6774, -0.7980, -0.5677],
        [ 1.4586,  4.3596, -0.2532, -0.7524,  0.6333,  3.4716]],
       dtype=torch.float64)
tensor([[-0.0286, -0.9756,  1.1493, -1.4482,  2.2093, -4.6093],
        [-1.3891,  1.7199,  3.8150, -6.3708,  1.0220,  3.5640],
        [-5.1578,  1.2497, -8.3352, -1.5765, -1.4194, -1.1862],
        [ 3.6623, -2.0293,  9.1039,  2.4872, -1.2557, -1.2425],
        [ 1.8573,  6.3075, -0.3938, -1.1714,  0.9472,  4.8638]],
       dtype=torch.float64)


> 以“_”结尾的操作会用结果替换原变量 

In [39]:
print(y[:,0])
print(y[0,:])

tensor([-0.0286, -1.3891, -5.1578,  3.6623,  1.8573], dtype=torch.float64)
tensor([-0.0286, -0.9756,  1.1493, -1.4482,  2.2093, -4.6093],
       dtype=torch.float64)


- torch.view:相当于numpy.reshape()操作

In [50]:
x=torch.randn(4,4)
y=x.view(1,16)
z = x.view(-1, 4) #-1: 从其他维度推算
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 4])
torch.Size([1, 16])
torch.Size([4, 4])


In [55]:
x=torch.randn(1)
print(x.item()) # 获取Tensors对应的python格式数值,只有(1)维的可以转

ValueError: only one element tensors can be converted to Python scalars

- numpy与torch变量互转: 所有的Tensor类型默认都是基于CPU，CharTensor 类型不支持到 NumPy 的转换.

In [57]:
a=torch.ones(5)
b=a.numpy()
print(a)
print(b)
a.add_(1) # b也会改变
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [59]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a)
print(b)
np.add(a,1,out=a) # b也会改变
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


- cuda张量

In [62]:
# 判断cuda是否可用 torch.cuda.is_avaliable()
if torch.cuda.is_available():
    device=torch.device('xxx') # 名为xxx的cuda对象
    y=torch.ones_like(x,device=device) # 在GPU中创建张量
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改