## 自动求导

- 深度学习本质上是通过反向传播求导数
- autograd提供自动微分功能
- 使用autograd时设置`tensor.requires_grad=True`

In [1]:
import torch

In [2]:
x=torch.randn(5,5,requires_grad=True)
x

tensor([[ 0.4105,  0.7196, -0.2166, -0.3294,  0.7362],
        [ 1.0934,  1.2342, -1.0429, -1.0907,  0.1891],
        [-1.7521, -0.9292, -0.2699,  1.8898,  1.4555],
        [-1.2967, -1.1645,  1.6761,  0.5552, -0.6375],
        [-0.3566,  1.8279, -1.4839, -0.5166, -0.4827]], requires_grad=True)

In [3]:
y=torch.randn(5,5,requires_grad=True)

In [6]:
z=torch.sum(x+y)
z

tensor(3.5590, grad_fn=<SumBackward0>)

In [7]:
z.backward()

In [8]:
print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [18]:
x=torch.rand(5,5,requires_grad=True)
y=torch.rand(5,5,requires_grad=True)
z=x**2+y**3
print(x)
print(y)
print(z)

tensor([[0.6106, 0.4548, 0.4084, 0.5060, 0.5793],
        [0.8542, 0.6751, 0.0926, 0.1542, 0.7551],
        [0.6411, 0.6217, 0.0663, 0.3985, 0.9624],
        [0.5263, 0.7247, 0.7745, 0.1994, 0.5677],
        [0.0161, 0.2196, 0.9854, 0.2293, 0.7126]], requires_grad=True)
tensor([[0.4278, 0.8833, 0.2222, 0.6758, 0.2172],
        [0.5271, 0.3302, 0.6036, 0.3423, 0.0234],
        [0.9831, 0.9291, 0.5055, 0.7897, 0.7991],
        [0.5587, 0.5999, 0.3694, 0.7713, 0.3255],
        [0.2002, 0.2498, 0.8083, 0.5847, 0.0296]], requires_grad=True)
tensor([[0.4511, 0.8960, 0.1777, 0.5647, 0.3458],
        [0.8762, 0.4917, 0.2285, 0.0639, 0.5702],
        [1.3611, 1.1885, 0.1336, 0.6513, 1.4364],
        [0.4514, 0.7411, 0.6503, 0.4987, 0.3567],
        [0.0083, 0.0638, 1.4992, 0.2524, 0.5079]], grad_fn=<AddBackward0>)


In [19]:
#print(torch.ones_like(x))
z.backward(torch.ones_like(x))
print(x.grad)

tensor([[1.2212, 0.9097, 0.8167, 1.0120, 1.1586],
        [1.7085, 1.3501, 0.1852, 0.3084, 1.5102],
        [1.2822, 1.2433, 0.1325, 0.7970, 1.9248],
        [1.0525, 1.4494, 1.5491, 0.3989, 1.1354],
        [0.0323, 0.4392, 1.9709, 0.4585, 1.4252]])


In [ ]:
- `with torch.no_grad()`:禁止对已设置requires_grad=True的张量进行自动求导。