## Autograd: 自动求导机制

- `.requires_grad`
     - 设置张量的属性`.requires_grad`为True时，可以跟踪该张量的所有梯度变换过程。
     - 计算完成后，可调用`.backward()`，自动计算所有的梯度。该Tensor的所有梯度会自动累计到.grad属性
- `.detach()`
     - 将张量与计算历史记录分离，禁止跟踪它将来的计算记录
- `with torch.no_grad()`
     - 防止跟踪历史记录，可用于评估等不需要梯度计算的过程
- `Function`
     - 每个张量都有一个.grad_fn属性，这个属性创建了Tensor的Function

In [3]:
import torch

In [5]:
x=torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [10]:
z=y*y*3 # Tensor的*要维度一致
out=z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [11]:
a=torch.randn(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [12]:
out.backward()

In [13]:
print(x.grad)
print(y.grad) 
print(z.grad) 

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
None
None


In [63]:
x=torch.randn(3,requires_grad=True)
y=x*2
print(y)
print(y.data)
print(y.data.norm()) 
# 计算y值得二范数
while y.data.norm()<1000:
    y=y*2
print(y)

tensor([4.6030, 0.7516, 3.6041], grad_fn=<MulBackward0>)
tensor([4.6030, 0.7516, 3.6041])
tensor(5.8942)
tensor([1178.3732,  192.4036,  922.6443], grad_fn=<MulBackward0>)


In [64]:
#gradients=torch.tensor([1.0, 0.1, 0.0001],dtype=torch.float)
#y.backward(gradients)
y.backward(torch.tensor([0.01, 0.1, 1],dtype=torch.float))
print(y[0].data/x[0].data) # y=512x
print(x.grad)
"""
[[0.01,0.1,1]*[[512,0,0],[0,512,0],[0,0,512]])^T
"""[]

tensor(512.)
tensor([  5.1200,  51.2000, 512.0000])


In [44]:
a=torch.FloatTensor([[2,4]])
a.requires_grad_(requires_grad=True)
b=torch.zeros(1,2)
b[0,0]=a[0,0]**2+a[0,1]
b[0,1]=a[0,1]**3+a[0,0]
out=b*2
# backward需要传入和out维度一样的矩阵
out.backward(torch.FloatTensor([[1,1]]))

In [46]:
print("input:",a.data)
print("output:",out.data)
print('input gradients:',a.grad)

input: tensor([[2., 4.]])
output: tensor([[ 16., 132.]])
input gradients: tensor([[10., 98.]])


In [65]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
	print((x ** 2).requires_grad)

True
True
False
