## Pytorch 基础：张量

In [1]:
import torch
import numpy as np
torch.__version__

'1.1.0'

- 张量(Tensor)，pytorch中的基础运算单位，与numpy的ndarray相同，表示一个多维矩阵。与np.ndarray最大的区别是Tensor可以在gpu上运行

In [2]:
x=torch.randn(2,3)
x

tensor([[-0.2290,  1.0975,  1.3688],
        [-1.0511, -1.4172, -0.7095]])

In [3]:
# shape和size()都用来获取Tensor的维度
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


在同构的意义下，第零阶张量(秩r=0)为标量(Scalar);第一阶张量(秩r=1)为向量(Vector);第二阶张量(秩r=2)为矩阵(Matrix);第三阶以上统称为多维张量。

In [5]:
# 多维张量
multidimensional = torch.randn(2,3,4)
print(multidimensional)

tensor([[[-0.5429,  0.7061, -1.2773, -0.1267],
         [ 0.1533,  0.7841, -2.8851,  0.3526],
         [-0.7783,  0.0732, -0.5997, -0.3498]],

        [[ 1.8963, -0.8403, -1.5102,  2.3071],
         [-0.3436,  0.8478,  2.8932,  0.0065],
         [ 0.5201,  1.6006, -1.5135, -1.0576]]])


In [7]:
# 矩阵
matrix=torch.randn(2,3)
print(matrix)
print(matrix.size())

tensor([[ 0.8280,  1.2189, -0.7991],
        [ 0.0568, -0.2447,  0.9181]])
torch.Size([2, 3])


In [8]:
# 向量
vector=torch.randn(4)
print(vector)
print(vector.size())

tensor([-0.1661, -0.9011, -1.2997, -0.8827])
torch.Size([4])


In [11]:
# 标量
scalar=torch.tensor(3.1415926)
print(scalar)
print(scalar.size())
print(scalar.item())  # 使用item()直接从标量中取值

tensor(3.1416)
torch.Size([])
3.141592502593994


In [15]:
# 只有一个元素的Tensor也可以使用item()
tensor=torch.tensor([[[3.1415162],[1]],[[1],[1]]])
print(tensor)
print(tensor.size())
print(tensor[0][0][0].item())

tensor([[[3.1415],
         [1.0000]],

        [[1.0000],
         [1.0000]]])
torch.Size([2, 2, 1])
3.1415162086486816


## 基本类型

- 32位浮点型: torch.FloatTensor(默认)
- 64位浮点型: torch.DoubleTensor
- 64位整型: torch.LongTensor
- 32位整型: torch.IntTensor
- 16位整型: torch.ShortTensor

In [22]:
long=tensor.long() # 将张量tensor投射成long类型
print(long.dtype)
print(long)

torch.int64
tensor([[[3],
         [1]],

        [[1],
         [1]]])


In [23]:
half_t=tensor.half() # 将张量tensor投射成半精度浮点类型
print(half_t.dtype)
print(half_t)

torch.float16
tensor([[[3.1406],
         [1.0000]],

        [[1.0000],
         [1.0000]]], dtype=torch.float16)


In [24]:
int_t=tensor.int()
print(int_t.dtype)
print(int_t)

torch.int32
tensor([[[3],
         [1]],

        [[1],
         [1]]], dtype=torch.int32)


In [25]:
float_t = tensor.float()
print(float_t.dtype)
print(float_t)

torch.float32
tensor([[[3.1415],
         [1.0000]],

        [[1.0000],
         [1.0000]]])


In [26]:
short_t = tensor.short()
print(short_t.dtype)
print(short_t)

torch.int16
tensor([[[3],
         [1]],

        [[1],
         [1]]], dtype=torch.int16)


In [27]:
char_t = tensor.char()
print(char_t.dtype) #8位int
print(char_t)

torch.int8
tensor([[[3],
         [1]],

        [[1],
         [1]]], dtype=torch.int8)


In [28]:
byte_t=tensor.byte()
print(byte_t.dtype) #无符号8位
print(byte_t)

torch.uint8
tensor([[[3],
         [1]],

        [[1],
         [1]]], dtype=torch.uint8)


- numpy转换: `.numpy(),from_numpy()`。通过这两个方法转换的tensor/ndarray其中一个改变，另外一个也跟着改变

In [32]:
a=torch.randn(3,2)
n=a.numpy()
print(n)

[[-0.53444076 -0.955656  ]
 [ 0.05717833 -0.8101765 ]
 [-0.07463469 -0.9990818 ]]


In [33]:
torch_a=torch.from_numpy(n)
print(torch_a)

tensor([[-0.5344, -0.9557],
        [ 0.0572, -0.8102],
        [-0.0746, -0.9991]])


## 设备间转换:
 - `.cuda()`: tensor转到gpu上(只有一块gpu);
 - `.to()`: 多gpu时可使用to方法指定使用哪个设备
 - `.cpu()`: 将tensor转到cpu上

In [34]:
cpu_a=torch.randn(4,5)
cpu_a.type()

'torch.FloatTensor'

In [38]:
if torch.cuda.is_available():
    gpu_a=cpu_a.cuda() # cuda不存在时指定cuda()会报错
    gpu_a.type()
    cpu_b=gpu_a.cpu()
    cpu_b.type()

In [39]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


## 初始化

- 使用[0,1]均匀分布初始化

In [43]:
rnd=torch.rand(5,3)
print(rnd)

tensor([[0.2423, 0.7098, 0.3067],
        [0.5602, 0.3575, 0.0043],
        [0.3453, 0.5707, 0.3182],
        [0.2246, 0.4261, 0.7192],
        [0.2484, 0.5784, 0.3002]])


- 生成全1的tensor

In [47]:
one=torch.ones(2,2)
print(one)

tensor([[1., 1.],
        [1., 1.]])


- 生成全0的数据

In [48]:
zero=torch.zeros(2,2)
print(zero)

tensor([[0., 0.],
        [0., 0.]])


- 生成单位矩阵


In [52]:
eye=torch.eye(3,2)
print(eye)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.]])


- 使用均值为0方差为1的正态分布初始化

In [53]:
x=torch.randn(3,3)
print(x)

tensor([[-0.1956, -2.0436,  2.3679],
        [-0.7472,  1.6500,  1.8465],
        [-0.3698, -0.2404, -0.9299]])


## 常用方法

In [54]:
max_value,max_idx=torch.max(x,dim=1) # dim=1，按行取; dim=0，按列取; 
print(max_value,max_idx)

tensor([ 2.3679,  1.8465, -0.2404]) tensor([2, 2, 1])


In [55]:
max_value,max_idx=torch.max(x,dim=0)
print(max_value,max_idx)

tensor([-0.1956,  1.6500,  2.3679]) tensor([0, 1, 0])


In [56]:
sum_x = torch.sum(x, dim=1)  # dim=1，按行取; dim=0，按列取; 
print(sum_x)
sum_x = torch.sum(x, dim=0)  # dim=1，按行取; dim=0，按列取; 
print(sum_x)

tensor([ 0.1286,  2.7493, -1.5400])
tensor([-1.3126, -0.6340,  3.2845])


In [57]:
y=torch.randn(3,3)
z=x+y
print(z)

tensor([[ 0.3636, -1.6916,  2.1166],
        [-2.0041,  2.4978,  1.0890],
        [ 0.1588, -0.5293, -0.6800]])


In [58]:
print(x)
x.add_(y)
print(x)

tensor([[-0.1956, -2.0436,  2.3679],
        [-0.7472,  1.6500,  1.8465],
        [-0.3698, -0.2404, -0.9299]])
tensor([[ 0.3636, -1.6916,  2.1166],
        [-2.0041,  2.4978,  1.0890],
        [ 0.1588, -0.5293, -0.6800]])
